INSERT INTO GOODS (TITLE, PRICE) VALUES ('Pen', 2.00);

INSERT INTO GOODS (TITLE, PRICE) VALUES ('Pencil', 1.00);

INSERT INTO GOODS (TITLE, PRICE)VALUES ('Eraser', 3.00);

INSERT INTO GOODS (TITLE, PRICE)VALUES ('Notebook', 4.00);

